- name: Configuring the machine for navigation exercises
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Create practice directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /home/practice
        - /home/practice/Angron
        - /home/practice/Angron/Wargear
        - /home/practice/Angron/Wargear/Armour
        - /home/practice/Angron/Wargear/Weapons
        - /home/practice/Angron/Battles
        - /home/practice/Angron/Legion
        - /home/practice/Lorgar
        - /home/practice/Lorgar/Scriptorium
        - /home/practice/Lorgar/Daemonic_Gifts
        - /home/practice/Lorgar/Sermons
        - /home/practice/Lorgar/Disciples
        - /home/practice/Titus
        - /home/practice/Titus/Ultramar
        - /home/practice/Titus/Campaigns
        - /home/practice/Titus/Training
        - /home/practice/Titus/Equipment
        - /home/practice/Dante
        - /home/practice/Dante/Blood_Angels
        - /home/practice/Dante/Artefacts
        - /home/practice/Dante/Missions
        - /home/practice/Dante/Chapter_Command
    
    - name: Create practice files in directories
      file:
        path:  "{{ item.path }}"
        state: touch
        mode: '0644'
      loop:
        # Angron files
        - { path: '/home/practice/Angron/Wargear/Armour/Armour of Mars' }
        - { path: '/home/practice/Angron/Wargear/Armour/Butchers_Nails' }
        - { path: '/home/practice/Angron/Wargear/Weapons/Spinegrinder' }
        - { path: '/home/practice/Angron/Wargear/Weapons/Samniarus' }
        - { path: '/home/practice/Angron/Wargear/Weapons/Black blade' }
        - { path: '/home/practice/Angron/Wargear/Weapons/Widowmaker' }
        - { path: '/home/practice/Angron/Wargear/Weapons/Gorechild' }
        - { path: '/home/practice/Angron/Battles/Ghenna_Massacre' }
        - { path: '/home/practice/Angron/Battles/Nuceria_Uprising' }
        - { path: '/home/practice/Angron/Battles/Shadow_Crusade' }
        - { path: '/home/practice/Angron/Legion/World_Eaters_Structure' }
        - { path: '/home/practice/Angron/Legion/Berserker_Implants' }
        - { path: '/home/practice/Angron/Legion/Notable_Warriors' }
        # Lorgar files
        - { path: '/home/practice/Lorgar/Scriptorium/Book_of_Lorgar' }
        - { path: '/home/practice/Lorgar/Scriptorium/Lectitio_Divinitatus' }
        - { path: '/home/practice/Lorgar/Scriptorium/Chaos_Manuscripts' }
        - { path: '/home/practice/Lorgar/Scriptorium/Prophecies' }
        - { path: '/home/practice/Lorgar/Daemonic_Gifts/Illuminarum' }
        - { path: '/home/practice/Lorgar/Daemonic_Gifts/Chaos_Blessings' }
        - { path: '/home/practice/Lorgar/Sermons/Monarchia_Address' }
        - { path: '/home/practice/Lorgar/Sermons/Pilgrimage_of_Enlightenment' }
        - { path: '/home/practice/Lorgar/Disciples/Kor_Phaeron' }
        - { path: '/home/practice/Lorgar/Disciples/Erebus' }
        # Titus files
        - { path: '/home/practice/Titus/Ultramar/Codex_Astartes' }
        - { path: '/home/practice/Titus/Ultramar/Macragge_Layout' }
        - { path: '/home/practice/Titus/Ultramar/Defensive_Strategies' }
        - { path: '/home/practice/Titus/Campaigns/Defense_of_Ultramar' }
        - { path: '/home/practice/Titus/Campaigns/Plague_Wars' }
        - { path: '/home/practice/Titus/Campaigns/Tyrannic_War' }
        - { path: '/home/practice/Titus/Training/Tactical_Doctrines' }
        - { path: '/home/practice/Titus/Training/Weapons_Proficiency' }
        - { path: '/home/practice/Titus/Equipment/Mark_X_Armor' }
        - { path: '/home/practice/Titus/Equipment/Bolt_Rifle_Specs' }
        # Dante files
        - { path: '/home/practice/Dante/Blood_Angels/Chapter_Records' }
        - { path: '/home/practice/Dante/Blood_Angels/Flaw_Research' }
        - { path: '/home/practice/Dante/Blood_Angels/Successor_Chapters' }
        - { path: '/home/practice/Dante/Artefacts/Axe_Mortalis' }
        - { path: '/home/practice/Dante/Artefacts/Death_Mask' }
        - { path: '/home/practice/Dante/Artefacts/Perdition_Pistol' }
        - { path: '/home/practice/Dante/Missions/Cryptus_Campaign' }
        - { path: '/home/practice/Dante/Missions/Baal_Defense' }
        - { path: '/home/practice/Dante/Missions/Nephilim_Sector_Patrols' }
        - { path: '/home/practice/Dante/Chapter_Command/Sanguinary_Guard' }
        - { path: '/home/practice/Dante/Chapter_Command/Death_Company' }

    - name: Create hidden files for characters
      file:
        path: {{ item.path }}
        state: touch
        mode: '0644'
      loop:
        - { path: '/home/practice/.secret_inquisition_report' }
        - { path: '/home/practice/Angron/.hidden_nails' }
        - { path: '/home/practice/Angron/.rage_supression_techniques' }
        - { path: '/home/practice/Lorgar/.forbidden_texts' }
        - { path: '/home/practice/Lorgar/.chaos_communication_codes' }
        - { path: '/home/practice/Titus/.primaris_upgrade_plans' }
        - { path: '/home/practice/Titus/.secret_weapon_prototypes' }
        - { path: '/home/practice/Dante/.blood_chalice' }
        - { path: '/home/practice/Dante/.sanguinius_visions' }

    - name: Setup user for practice
      user:
        name: space_marine
        create_home: yes
        shell: /bin/bash
    
    - name: Set correct permissions
      file:
        path: /home/practice
        owner: space_marine
        group: space_marine
        recurse: yes